version: '3.8'

services:
  python-app:
    build: .
    ports:
      - "8887:8887"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: always
