version: "3.8"

services:
  node-app:
    build: .
    container_name: magic-calculator
    ports:
      - "8085:8085"  # Expose Node.js app on port 8085
    volumes:
      - .:/app
    environment:
      - PORT=8085
    command: ["node", "app.js"]
    restart: always
