version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
